#!/usr/bin/env bash
# project-to-sdd.sh — project the docs/ requirement spine into an SDD framework
# (OpenSpec or GitHub Spec Kit), preserving [RF-NN] tags for round-trip safety.
#
# Complement of the check_projection_drift MCP tool (v1.9.0): this GENERATES the
# projection skeleton; that one VERIFIES it stayed in sync. The source of truth
# stays in docs/ — the framework folder is a projection. See references/12-sdd-interop.md.
#
# Usage:
#   project-to-sdd.sh <feature-id-or-slug> [--target openspec|speckit] [--root docs] [--apply]
#
# Examples:
#   project-to-sdd.sh F-06                       # dry-run, openspec (default)
#   project-to-sdd.sh F-06 --target speckit --apply
#   project-to-sdd.sh rateio --apply             # match by slug substring
#
# Safety: DRY-RUN by default (prints the plan, writes nothing). --apply writes.
# Never overwrites an existing file (skips + warns). It scaffolds structure + the
# [RF-NN] tags + traceability; you fill the EARS prose, then run check_projection_drift.
set -Eeuo pipefail

# ---------- defaults ----------
ROOT="docs"
TARGET="openspec"
APPLY=0
FEATURE_ARG=""

# ---------- helpers ----------
c_reset=$'\033[0m'; c_grn=$'\033[32m'; c_yel=$'\033[33m'; c_cyn=$'\033[36m'; c_red=$'\033[31m'
info() { printf '%s%s%s\n' "$c_cyn" "$*" "$c_reset"; }
ok()   { printf '%s%s%s\n' "$c_grn" "$*" "$c_reset"; }
warn() { printf '%s%s%s\n' "$c_yel" "$*" "$c_reset"; }
err()  { printf '%s%s%s\n' "$c_red" "$*" "$c_reset" >&2; }
say()  { printf '%s\n' "$*"; }
usage() { sed -n '2,19p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit "${1:-0}"; }

# ---------- args ----------
while [ $# -gt 0 ]; do
  case "$1" in
    -h|--help)   usage 0 ;;
    --target)    TARGET="${2:-}"; shift 2 ;;
    --target=*)  TARGET="${1#*=}"; shift ;;
    --root)      ROOT="${2:-}"; shift 2 ;;
    --root=*)    ROOT="${1#*=}"; shift ;;
    --apply)     APPLY=1; shift ;;
    --)          shift; break ;;
    -*)          err "unknown option: $1"; usage 1 ;;
    *)           if [ -z "$FEATURE_ARG" ]; then FEATURE_ARG="$1"; else err "unexpected arg: $1"; usage 1; fi; shift ;;
  esac
done

[ -n "$FEATURE_ARG" ] || { err "missing <feature-id-or-slug>"; usage 1; }
case "$TARGET" in openspec|speckit) ;; *) err "invalid --target '$TARGET' (use openspec|speckit)"; usage 1 ;; esac

FEAT_DIR="$ROOT/backlog/features"
[ -d "$FEAT_DIR" ] || { err "no '$FEAT_DIR' — run from a project with the docs/ spine (assets/scaffold-structure.sh)"; exit 1; }

# ---------- locate the feature file (by id, by F-id prefix, or by slug substring) ----------
shopt -s nullglob
matches=()
for f in "$FEAT_DIR"/*.md; do
  base="$(basename "$f" .md)"
  [ "$base" = "_TEMPLATE" ] && continue
  case "$base" in
    "$FEATURE_ARG"|"$FEATURE_ARG"-*) matches+=("$f"); continue ;;
  esac
  case "$base" in *"$FEATURE_ARG"*) matches+=("$f") ;; esac
done
shopt -u nullglob
[ "${#matches[@]}" -ge 1 ] || { err "no feature file matching '$FEATURE_ARG' in $FEAT_DIR"; exit 1; }
if [ "${#matches[@]}" -gt 1 ]; then
  err "ambiguous '$FEATURE_ARG' — matches:"; printf '  %s\n' "${matches[@]}" >&2; exit 1
fi
FEAT_FILE="${matches[0]}"
FEAT_BASE="$(basename "$FEAT_FILE" .md)"                         # e.g. F-06-calculo-do-rateio

# ---------- extract artifacts (tag-based; tolerant) ----------
FEAT_ID="$(printf '%s' "$FEAT_BASE" | grep -oiE '^F-?[0-9]+' | head -1 || true)"
[ -n "$FEAT_ID" ] || FEAT_ID="$FEAT_BASE"
SLUG="${FEAT_BASE#"$FEAT_ID"-}"
[ -n "$SLUG" ] && [ "$SLUG" != "$FEAT_BASE" ] || SLUG="$FEAT_ID"
TITLE="$(grep -m1 '^# ' "$FEAT_FILE" | sed -E 's/^#[[:space:]]*//; s/^F-?[0-9]+[[:space:]]*[—-][[:space:]]*//')"
[ -n "$TITLE" ] || TITLE="$FEAT_ID"
EPIC="$(grep -oiE 'EP-[0-9]+' "$FEAT_FILE" | head -1 || true)"
RFS="$(grep -oiE 'RF-[0-9]+|RNF-[0-9]+' "$FEAT_FILE" | tr 'a-z' 'A-Z' | sort -u || true)"
CAS="$(grep -oE '\bCA[0-9]{2}\b' "$FEAT_FILE" | sort -u || true)"
TASKS="$(grep -oE 'T-[0-9]+\.[0-9]+\.[0-9]+[a-z]?|TX-[0-9]+' "$FEAT_FILE" | sort -u || true)"

BANNER="> ⚙️ Generated by \`assets/project-to-sdd.sh\` from the \`$ROOT/\` spine — **source of truth stays in \`$ROOT/\`**, this is a projection.
> Fill the EARS prose (\`references/11-ears.md\`), keep every \`[RF-NN]\` tag, then run the MCP tool \`check_projection_drift\` to verify no drift."

# ---------- report ----------
info "== project-to-sdd.sh =="
say  "feature=$FEAT_BASE  id=$FEAT_ID  slug=$SLUG  target=$TARGET  apply=$APPLY"
say  "title=$TITLE  epic=${EPIC:-<none>}"
say  "RF/RNF: $(printf '%s' "$RFS" | tr '\n' ' ')"
say  "CA:     $(printf '%s' "$CAS" | tr '\n' ' ')"
say  "Tasks:  $(printf '%s' "$TASKS" | tr '\n' ' ')"
[ "$APPLY" -eq 0 ] && warn "DRY-RUN — nothing written. Re-run with --apply." || true
say ""

# ---------- emit (dry-run aware, never overwrites) ----------
emit() {  # emit <path> <content>
  local path="$1" content="$2"
  if [ "$APPLY" -eq 0 ]; then say "  PLAN  $path"; return 0; fi
  if [ -e "$path" ]; then warn "  skip  $path (exists — not overwritten)"; return 0; fi
  mkdir -p -- "$(dirname -- "$path")"
  printf '%s\n' "$content" > "$path"
  ok "  write $path"
}

req_sections() {  # the per-RF requirement sections, [RF-NN] preserved
  if [ -z "$RFS" ]; then
    printf '_(no RF-NN tag found in the feature — check its "Requisitos atendidos" section)_\n'
    return
  fi
  while IFS= read -r rf; do
    [ -n "$rf" ] || continue
    printf '### [%s] <business title>\n\n' "$rf"
    printf 'TODO: EARS phrasing (references/11-ears.md) — `WHEN/QUANDO <trigger> THE SYSTEM SHALL/O SISTEMA DEVE <response>`. Keep the `[%s]` tag.\n' "$rf"
    printf 'Source of truth: `%s/requirements/RF/` (this RF lives in its module file).\n\n' "$ROOT"
  done <<< "$RFS"
}

ca_block() {
  if [ -z "$CAS" ]; then printf '_(no CANN ids found)_\n'; return; fi
  while IFS= read -r ca; do [ -n "$ca" ] && printf -- '- %s — TODO: testable rule\n' "$ca"; done <<< "$CAS"
}

tasks_block() {
  if [ -z "$TASKS" ]; then printf -- '- [ ] TODO: derive tasks from the feature\n'; return; fi
  while IFS= read -r t; do [ -n "$t" ] && printf -- '- [ ] %s\n' "$t"; done <<< "$TASKS"
}

spec_md() {
  printf '# %s  [%s]\n\n%s\n\n' "$TITLE" "$FEAT_ID" "$BANNER"
  printf '## Requirements\n\n'; req_sections
  printf '\n## Acceptance criteria\n\n'; ca_block
  printf '\n## Scenarios\n\n```gherkin\nCenário: <caminho feliz>\n  Dado <contexto>\n  Quando <ação>\n  Então <resultado observável>\n```\n'
}

# ---------- generate per target ----------
if [ "$TARGET" = "openspec" ]; then
  OUT="openspec/changes/$SLUG"
  info "[plan] OpenSpec change folder → $OUT/"
  emit "$OUT/proposal.md" "$(printf '# %s  [%s]\n\n%s\n\n## Why\n\nEpic %s. TODO: motivation + the G-NN business rules.\n\n## In scope\n\n%s\n\n## Out of scope\n\nTODO: explicitly list adjacent RF NOT in this change (OpenSpec'\''s highest-value field).\n' \
      "$TITLE" "$FEAT_ID" "$BANNER" "${EPIC:-<none>}" "$(printf '%s' "$RFS" | sed 's/^/- /')")"
  emit "$OUT/specs/spec.md" "$(spec_md)"
  emit "$OUT/design.md" "$(printf '# Design — %s  [%s]\n\n%s\n\nTODO: technical approach. ADRs live in `%s/planning/adrs/` (tier-1) and `%s/specs/<feature>/adrs/` (tier-2). Reference them here; do not duplicate.\n' "$TITLE" "$FEAT_ID" "$BANNER" "$ROOT" "$ROOT")"
  emit "$OUT/tasks.md" "$(printf '# Tasks — %s  [%s]\n\n%s\n\n%s\n' "$TITLE" "$FEAT_ID" "$BANNER" "$(tasks_block)")"
else
  OUT="specs/$SLUG"
  info "[plan] Spec Kit feature dir → $OUT/"
  emit "$OUT/spec.md" "$(spec_md)"
  emit "$OUT/plan.md" "$(printf '# Plan — %s  [%s]\n\n%s\n\nTODO: design decisions + G-NN constraints. ADRs in `%s/planning/adrs/` (+ tier-2 `%s/specs/<feature>/adrs/`).\n' "$TITLE" "$FEAT_ID" "$BANNER" "$ROOT" "$ROOT")"
  emit "$OUT/tasks.md" "$(printf '# Tasks — %s  [%s]\n\n%s\n\n%s\n' "$TITLE" "$FEAT_ID" "$BANNER" "$(tasks_block)")"
  emit ".specify/memory/constitution.md" "$(printf '# Constitution (write-once)\n\n%s\n\nHard conventions: the 10 rules of `%s` (`references/05-convencoes-interpop.md`). Ethics guardrails: SBC 002/2024 (`references/09-etica-sbc.md`). Naming/ID/priority rules are non-negotiable across every feature.\n' "$BANNER" "engenharia-de-requisitos" "$ROOT")"
fi

say ""
if [ "$APPLY" -eq 1 ]; then
  ok "Done. Projection scaffolded under '$OUT/'."
  say "NEXT: fill the EARS prose per [RF-NN], then verify with the MCP tool:"
  say "  check_projection_drift(requirements_dir='$ROOT/requirements', projection_dir='$([ "$TARGET" = openspec ] && echo openspec || echo specs)')"
else
  warn "Dry-run complete. Re-run with --apply to write the projection."
fi
